### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by adrian-schnell** [tjespers/tinkerwell-interpreters#1]
Thanks for this tool!! <3

but i'm having some problems with the local setup.
If I'm not changing the ports of redis and the db in my .env to the public ports, I'm getting connection errors:

`Predis\Connection\ConnectionException  : Connection refused [tcp://127.0.0.1:6379]`

but then I'm not able to use artisan ore something else in the project.

how can I conntect the containers correctly?

I'm using docker-compose v2.

```
tinkerwell-exec:
    image: php:7.4-cli-alpine
    networks:
      - ka_network
    links:
      - redis
      - db
    volumes:
      # Mount the project root in a known location
      - ./:/code:delegated
      # Mount the file that will hold the contents of the tinkerwell terminal
      - ./.tinkerwell/tinkerscript.txt:/tmp/tinkerwell-src.txt
      # Binds MacOS tinkerwell app into the container
      - /Applications/Tinkerwell.app/Contents/Resources/tinkerwell:/run/app:ro
    working_dir: /code
    command: /bin/sh -c while :; do sleep 10; done

  redis:
    container_name: ka_redis
    image: redis:3.2-alpine
    restart: always
    networks:
      - ka_network
    ports:
      - 36379:6379
    volumes:
      - redisdata:/data

  db:
    container_name: ka_db
    image: mariadb:10.4
    restart: always
    networks:
      - ka_network
    ports:
      - "33066:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=my_db"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  web:
    container_name: ka_web
    image: nginx:1.13-alpine
    working_dir: /var/www/html
    restart: always
    networks:
      - ka_network
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro,delegated
      - ./storage/app/public:/var/www/html/public/storage:delegated
    depends_on:
      - app
      - worker-default

  app: &php
    container_name: app
    image: php/php:7.3-fpm
    restart: on-failure
    user: www-data
    networks:
      - ka_network
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./docker/php.ini:/usr/local/etc/php/conf.d/docker-php.ini:ro
      - composertmp:/tmp
    environment:
      - "DB_HOST=db"
      - "REDIS_HOST=redis"
      - "DB_DATABASE=my_db"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=secret"
      - "MAIL_HOST=email"
      - "MAIL_PORT=1025"
      - "COMPOSER_HOME=/tmp"
    depends_on:
      - db
      - redis
      - email

networks:
      - ka_network:
```
